<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>QR Codes - ESD Equipment</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Segoe UI', Arial, sans-serif;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #1a56db;
        }
        .header h1 {
            font-size: 24px;
            color: #1a56db;
            margin-bottom: 5px;
        }
        .header p {
            font-size: 12px;
            color: #666;
        }
        .info {
            text-align: right;
            font-size: 10px;
            color: #999;
            margin-bottom: 20px;
        }
        .qr-grid {
            display: grid;
            grid-template-columns: repeat(5, 1fr);
            gap: 20px;
            page-break-inside: avoid;
        }
        .qr-item {
            text-align: center;
            page-break-inside: avoid;
            break-inside: avoid;
            border: 1px solid #e0e0e0;
            border-radius: 8px;
            padding: 15px;
        }
        .qr-item img {
            width: 120px;
            height: 120px;
            display: block;
            margin: 0 auto;
        }
        .register-no {
            font-size: 10px;
            font-weight: bold;
            margin-top: 10px;
            word-break: break-all;
            color: #333;
        }
        .model-label {
            font-size: 9px;
            color: #666;
            margin-top: 5px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 9px;
            color: #999;
            padding-top: 10px;
            border-top: 1px solid #eee;
        }
        @page {
            size: A4;
            margin: 1cm;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>ESD Equipment QR Codes</h1>
        <p>Electrostatic Discharge Equipment Identification System</p>
    </div>
    
    <div class="info">
        Printed: {{ $date }} | Total: {{ $total }} items
    </div>
    
    <div class="qr-grid">
        @foreach($items as $item)
            <div class="qr-item">
                @if($item['qr_base64'])
                    <img src="{{ $item['qr_base64'] }}" alt="QR Code">
                @else
                    <div style="width:120px;height:120px;background:#f0f0f0;display:flex;align-items:center;justify-content:center;margin:0 auto;">
                        <span style="font-size:10px;">{{ $item['register_no'] }}</span>
                    </div>
                @endif
                <div class="register-no">{{ $item['register_no'] }}</div>
                <div class="model-label">{{ $modelLabels[$item['model']] }}</div>
            </div>
        @endforeach
    </div>
    
    <div class="footer">
        Generated by ESD QR Code Printer System | {{ date('Y-m-d H:i:s') }}
    </div>
</body>
</html>