<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Arial', sans-serif;
            font-size: 9pt;
            line-height: 1.3;
            margin: 15px;
            padding: 0;
        }
        
        .container {
            width: 100%;
            margin: 0 auto;
        }
        
        .header {
            text-align: center;
            margin-bottom: 15px;
            border-bottom: 2px solid #333;
            padding-bottom: 8px;
        }
        
        .header h1 {
            margin: 0;
            font-size: 16pt;
            color: #1a56db;
        }
        
        .header h3 {
            margin: 3px 0;
            font-size: 11pt;
            color: #666;
        }
        
        .report-info {
            margin-bottom: 15px;
            padding: 8px;
            background: #f3f4f6;
            border-radius: 5px;
            font-size: 8pt;
        }
        
        .report-info table {
            width: 100%;
        }
        
        .report-info td {
            padding: 2px 5px;
        }
        
        .report-info td:first-child {
            font-weight: bold;
            width: 100px;
        }
        
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 8pt;
        }
        
        table.data-table th {
            background: #1a56db;
            color: white;
            padding: 6px 4px;
            text-align: left;
            border: 1px solid #ddd;
            font-weight: bold;
        }
        
        table.data-table td {
            padding: 5px 4px;
            border: 1px solid #ddd;
            vertical-align: top;
        }
        
        table.data-table tr:nth-child(even) {
            background: #f9fafb;
        }
        
        .footer {
            margin-top: 15px;
            text-align: center;
            font-size: 7pt;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 8px;
            position: fixed;
            bottom: 10px;
            left: 0;
            right: 0;
        }
        
        .badge-ok {
            color: #059669;
            font-weight: bold;
        }
        
        .badge-ng {
            color: #dc2626;
            font-weight: bold;
        }
        
        .text-center {
            text-align: center;
        }
        
        .text-left {
            text-align: left;
        }
        
        .text-right {
            text-align: right;
        }
        
        .wrap-text {
            word-wrap: break-word;
            word-break: break-all;
            white-space: normal;
        }
        
        /* Untuk mencegah teks terpotong */
        .no-wrap {
            white-space: nowrap;
        }
        
        /* Ukuran kolom */
        .col-no { width: 5%; }
        .col-register { width: 12%; }
        .col-area { width: 10%; }
        .col-location { width: 10%; }
        .col-b1 { width: 10%; }
        .col-judgement { width: 6%; }
        .col-remarks { width: 15%; }
        .col-date { width: 8%; }
        .col-next-date { width: 8%; }
        .col-checked { width: 10%; }
        
        @page {
            size: A4 landscape;
            margin: 15px;
        }
        
        /* Untuk print */
        @media print {
            body {
                margin: 0;
                padding: 0;
            }
            .footer {
                position: fixed;
                bottom: 0;
            }
            .page-break {
                page-break-before: always;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{{ $title }}</h1>
            <h3>Electrostatic Discharge - Flooring Measurement Report</h3>
        </div>
        
        <div class="report-info">
            <table>
                <tr>
                    <td>Generated By:</td>
                    <td>{{ $generated_by }}</td>
                    <td>Generated At:</td>
                    <td>{{ $generated_at }}</td>
                </tr>
                @if($register_no)
                <tr>
                    <td>Register No Filter:</td>
                    <td colspan="3">{{ $register_no }}</td>
                </tr>
                @endif
                @if($date_from || $date_until)
                <tr>
                    <td>Date Range:</td>
                    <td colspan="3">
                        {{ $date_from ? \Carbon\Carbon::parse($date_from)->format('d M Y') : 'Start' }} 
                        to 
                        {{ $date_until ? \Carbon\Carbon::parse($date_until)->format('d M Y') : 'End' }}
                    </td>
                </tr>
                @endif
                <tr>
                    <td>Total Records:</td>
                    <td colspan="3">{{ $details->count() }} measurement(s)</td>
                </tr>
            </table>
        </div>
        
        <table class="data-table">
            <thead>
                <tr>
                    <th class="col-no">#</th>
                    <th class="col-register">Register No</th>
                    <th class="col-area">Area</th>
                    <th class="col-location">Location</th>
                    <th class="col-b1">B1 Result</th>
                    <th class="col-judgement">Judgement</th>
                    <th class="col-remarks">Remarks</th>
                    <th class="col-date">Date</th>
                    <th class="col-next-date">Next Date</th>
                    <th class="col-checked">Checked By</th>
                </tr>
            </thead>
            <tbody>
                @forelse($details as $index => $detail)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td class="wrap-text">{{ $detail->flooring->register_no ?? 'N/A' }}</td>
                    <td class="wrap-text">{{ $detail->flooring->area ?? 'N/A' }}</td>
                    <td class="wrap-text">{{ $detail->flooring->location ?? 'N/A' }}</td>
                    <td class="text-center">{{ $detail->b1_scientific ?? '-' }}</td>
                    <td class="text-center">
                        <span class="{{ $detail->judgement == 'OK' ? 'badge-ok' : 'badge-ng' }}">
                            {{ $detail->judgement ?? '-' }}
                        </span>
                    </td>
                    <td class="wrap-text">{{ $detail->remarks ?? '-' }}</td>
                    <td class="text-center">{{ $detail->created_at ? $detail->created_at->format('d M Y') : '-' }}</td>
                    <td class="text-center">{{ $detail->next_date ? \Carbon\Carbon::parse($detail->next_date)->format('d M Y') : '-' }}</td>
                    <td class="wrap-text">{{ $detail->creator->name ?? 'N/A' }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="10" class="text-center" style="padding: 20px;">
                        No data found for the selected filters.
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
        
        <div class="footer">
            This is a computer generated report. No signature required.
            <br>Page {PAGE_NUM} of {PAGE_COUNT}
        </div>
    </div>
</body>
</html>